In [2]:
import pandas as pd
import nltk

In [ ]:
'''
import sys
!{sys.executable} -m pip install --upgrade pip

'''

In [3]:
# This takes a few minutes
with open('review.json', 'r+') as f:
        data = f.readlines()
data = map(lambda x: x.rstrip(), data)       # removes trailing \n's
data_json_str = "[" + ','.join(data) + "]"  
review_df = pd.read_json(data_json_str)

In [5]:
review_df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,Q1sbwvVQXV2734tPgoKj4Q,hG7b0MtEbXx5QzbzE6C_VA,ujmEBvifdJM6h6RLv4wQIg,1,6,1,0,Total bill for this horrible service? Over $8G...,2013-05-07 04:34:36
1,GJXCdrto3ASJOqKeVWPi6Q,yXQM5uF2jS6es16SJzNHfg,NZnhc2sEQy3RmzKTZnqtwQ,5,0,0,0,I *adore* Travis at the Hard Rock's new Kelly ...,2017-01-14 21:30:33
2,2TzJjDVDEuAW6MR5Vuc1ug,n6-Gk65cPZL6Uz8qRm3NYw,WTqjgwHlXbSFevF32_DJVw,5,3,0,0,I have to say that this office really has it t...,2016-11-09 20:09:03
3,yi0R0Ugj_xUx_Nek0-_Qig,dacAIZ6fTM6mqwW5uxkskg,ikCg8xy5JIg_NGPx-MSIDA,5,0,0,0,Went in for a lunch. Steak sandwich was delici...,2018-01-09 20:56:38
4,11a8sVPMUFtaC7_ABRkmtw,ssoyf2_x0EQMed6fgHeMyQ,b1b1eb3uo-w561D0ZfCEiQ,1,7,0,0,Today was my second out of three sessions I ha...,2018-01-30 23:07:38
...,...,...,...,...,...,...,...,...,...
6685895,0pCaq1hqAViS2N6ldlp_sQ,Xu_YazIajfsc7SRj1wJ6Mg,RXBFk3tVBxiTf3uOt9KExQ,5,1,0,0,I have been coming here for years and this pla...,2018-07-03 12:17:27
6685896,jPCXuSBbI_cPocgoNBhdkg,V6BjjQICDO4q7TT3ZhaPWw,yA6dKNm_zl1ucZCnwW8ZCg,1,13,11,5,I think this owner and the owner of Amy's Baki...,2013-05-22 15:32:08
6685897,zwzO3yPdGbdgGy3-XQ0SWg,PFiIECX8wuvi7P-1mCvIjA,a192hdM0_UVCYLwPJv1Qwg,5,0,0,0,"Off the grid Mexican in Vegas. Very tasty, qua...",2018-11-13 21:15:20
6685898,o8Nc2BJhKJXM6tRHJDRuPA,wu5R5_N7q5iqCBh6NBX26Q,kOo4ZY2UQAX4j312mzQ8mA,5,1,1,1,We hired Taco Naco to cater our family party a...,2018-08-13 18:09:16
6685899,OKmOLFwtI-NjofTHAGzv1Q,Ej3mCvjcwVXCSPB_avIfjQ,PkqN5st3zZ_Xce_5QlBtNQ,3,2,0,0,Having just come back from Hawaii a few months...,2018-11-12 20:25:32

In [6]:
with open('business.json', 'r+') as f:
        data = f.readlines()
data = map(lambda x: x.rstrip(), data)       # removes trailing \n's
data_json_str = "[" + ','.join(data) + "]"  
business_df = pd.read_json(data_json_str)

In [7]:
business_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,1SWheh84yJXfytovILXOAQ,Arizona Biltmore Golf Club,2818 E Camino Acequia Drive,Phoenix,AZ,85016,33.522143,-112.018481,3.0,5,0,{'GoodForKids': 'False'},"Golf, Active Life",None
1,QXAEGFB4oINsVuTFxEYKFQ,Emerald Chinese Restaurant,30 Eglinton Avenue W,Mississauga,ON,L5R 3E7,43.605499,-79.652289,2.5,128,1,"{'RestaurantsReservations': 'True', 'GoodForMe...","Specialty Food, Restaurants, Dim Sum, Imported...","{'Monday': '9:0-0:0', 'Tuesday': '9:0-0:0', 'W..."
2,gnKjwL_1w79qoiV3IC_xQQ,Musashi Japanese Restaurant,"10110 Johnston Rd, Ste 15",Charlotte,NC,28210,35.092564,-80.859132,4.0,170,1,"{'GoodForKids': 'True', 'NoiseLevel': 'u'avera...","Sushi Bars, Restaurants, Japanese","{'Monday': '17:30-21:30', 'Wednesday': '17:30-..."
3,xvX2CttrVhyG2z1dFg_0xw,Farmers Insurance - Paul Lorenz,"15655 W Roosevelt St, Ste 237",Goodyear,AZ,85338,33.455613,-112.395596,5.0,3,1,None,"Insurance, Financial Services","{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ..."
4,HhyxOkGAM07SRYtlQ4wMFQ,Queen City Plumbing,"4209 Stuart Andrew Blvd, Ste F",Charlotte,NC,28217,35.190012,-80.887223,4.0,4,1,"{'BusinessAcceptsBitcoin': 'False', 'ByAppoint...","Plumbing, Shopping, Local Services, Home Servi...","{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192604,nqb4kWcOwp8bFxzfvaDpZQ,Sanderson Plumbing,,North Las Vegas,NV,89032,36.213732,-115.177059,5.0,9,1,{'BusinessAcceptsCreditCards': 'True'},"Water Purification Services, Water Heater Inst...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
192605,vY2nLU5K20Pee-FdG0br1g,Chapters,17440 Yonge Street,Newmarket,ON,L3Y 6Y9,44.052658,-79.481850,4.5,3,1,"{'RestaurantsPriceRange2': '2', 'BikeParking':...","Books, Mags, Music & Video, Shopping",None
192606,MiEyUDKTjeci5TMfxVZPpg,Phoenix Pavers,21230 N 22nd St,Phoenix,AZ,85024,33.679992,-112.035569,4.5,14,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Home Services, Contractors, Landscaping, Mason...","{'Monday': '7:0-15:0', 'Tuesday': '7:0-15:0', ..."
192607,zNMupayB2jEHVDOji8sxoQ,Beasley's Barber Shop,4406 E Main St,Mesa,AZ,85205,33.416137,-111.735743,4.5,15,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Beauty & Spas, Barbers","{'Tuesday': '8:30-17:30', 'Wednesday': '8:30-1..."
192608,c1f_VAX1KIK8-JoVhjbYOw,Oriental Relax,3735 S Las Vegas Blvd,Las Vegas,NV,89109,36.107267,-115.171920,4.0,3,0,"{'BikeParking': 'False', 'RestaurantsPriceRang...","Massage, Beauty & Spas","{'Monday': '10:0-0:0', 'Tuesday': '10:0-0:0', ..."

In [30]:
business_df = business_df[(business_df['state']=='NV')| (business_df['state']=='AZ') | (business_df['state']=='AZ')]

92998

In [33]:
merged_df = review_df.merge(business_df, on='business_id' ,how='right')

In [34]:
merged_df

,review_id,user_id,business_id,stars_x,useful,funny,cool,text,date,name,...,state,postal_code,latitude,longitude,stars_y,review_count,is_open,attributes,categories,hours
0,Q1sbwvVQXV2734tPgoKj4Q,hG7b0MtEbXx5QzbzE6C_VA,ujmEBvifdJM6h6RLv4wQIg,1.0,6.0,1.0,0.0,Total bill for this horrible service? Over $8G...,2013-05-07 04:34:36,MountainView Hospital,...,NV,89128,36.215546,-115.248798,2.5,238,1,"{'ByAppointmentOnly': 'False', 'GoodForKids': ...","Fitness & Instruction, Doctors, Health & Medic...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
1,8Edv5pKe5lOBoN5UZTUI1w,RBXSJA372ilErzNwz0jXvQ,ujmEBvifdJM6h6RLv4wQIg,4.0,0.0,0.0,0.0,My family has used this ER four times in the p...,2017-02-09 06:45:18,MountainView Hospital,...,NV,89128,36.215546,-115.248798,2.5,238,1,"{'ByAppointmentOnly': 'False', 'GoodForKids': ...","Fitness & Instruction, Doctors, Health & Medic...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
2,kEs5u0cGPtiSQCLW7b0l9g,x3brMMbJrAW9PwW5A6YL5w,ujmEBvifdJM6h6RLv4wQIg,1.0,1.0,0.0,0.0,I have never been more disappointed by the car...,2018-08-14 05:25:33,MountainView Hospital,...,NV,89128,36.215546,-115.248798,2.5,238,1,"{'ByAppointmentOnly': 'False', 'GoodForKids': ...","Fitness & Instruction, Doctors, Health & Medic...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
3,Pm6qydbW58BB0zdWCPlBmg,Skzdl0sWhW88525a1vr59g,ujmEBvifdJM6h6RLv4wQIg,1.0,3.0,0.0,0.0,"Went in for a broken finger, was asked if I wa...",2018-05-08 19:27:59,MountainView Hospital,...,NV,89128,36.215546,-115.248798,2.5,238,1,"{'ByAppointmentOnly': 'False', 'GoodForKids': ...","Fitness & Instruction, Doctors, Health & Medic...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
4,QWJVYwNxUY_Plu4Ipz33_A,3Y25VDfnQVcuc33T-U3Z6A,ujmEBvifdJM6h6RLv4wQIg,5.0,1.0,0.0,0.0,My mother was at Mountain View for nearly two ...,2014-10-11 06:57:18,MountainView Hospital,...,NV,89128,36.215546,-115.248798,2.5,238,1,"{'ByAppointmentOnly': 'False', 'GoodForKids': ...","Fitness & Instruction, Doctors, Health & Medic...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4403440,qByVVhoG6p_LhPAwnyZo0w,WhVnaHLcTVj3Vg8bw0wssA,vK6rLsSr6ft87S8C_Pvv2Q,2.0,1.0,0.0,0.0,A mixed bag for those looking for short-term e...,2018-10-01 17:23:10,Adecco Staffing,...,AZ,85014,33.516067,-112.063520,1.5,3,1,None,"Professional Services, Employment Agencies","{'Monday': '8:0-17:30', 'Tuesday': '8:0-17:30'..."
4403441,2s3mrO7bgGjG01gmhqdDzA,_fGju43E8HBbNbvRwT0JfQ,vK6rLsSr6ft87S8C_Pvv2Q,2.0,4.0,0.0,0.0,No response from most staff members. You fill...,2014-08-20 16:34:15,Adecco Staffing,...,AZ,85014,33.516067,-112.063520,1.5,3,1,None,"Professional Services, Employment Agencies","{'Monday': '8:0-17:30', 'Tuesday': '8:0-17:30'..."
4403442,NaN,NaN,YSilq0Was9b4Q7oId_gUUw,NaN,NaN,NaN,NaN,NaN,NaT,Zelma Basha Sameri Gallery of Western and Nati...,...,AZ,85248,33.243596,-111.859274,5.0,4,1,"{'BusinessParking': '{'garage': False, 'street...","Art Galleries, Shopping, Arts & Entertainment",None
4403443,NaN,NaN,Pah1N0Di1WA3wsI5TYkY7w,NaN,NaN,NaN,NaN,NaN,NaT,Gem and Bead Mall,...,NV,89119,36.069866,-115.125714,4.5,7,1,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Shopping, Hobby Shops, Jewelry, Arts & Crafts,...","{'Monday': '10:0-18:0', 'Tuesday': '10:0-18:0'..."
4403444,NaN,NaN,W6q7CANl3UbQa5hGCYU5OQ,NaN,NaN,NaN,NaN,NaN,NaT,Starbucks,...,AZ,85323,33.433932,-112.304625,4.0,17,1,"{'Caters': 'False', 'RestaurantsTakeOut': 'Tru...","Food, Coffee & Tea",None